# Конфигурация приложения, которая используется до запуска cloud config
spring:
  application:
    name: 's3-service'

  profiles:
    active: '${PROFILE:default}'

  config:
    import: 'configserver:${CONFIG_SERVER_URI:http://localhost:8071}'