spring:
  application:
    name: 'config-server'
# Указываем, где хранятся файлы конфигурации Spring Cloud Configuration Server
  profiles:
    # Профили перечисляются в порядке возрастания приоритета
    active: git

  # Лучше сделать один репозиторий с конфигурацией под каждый из микросервисов, а каталоги -- под каждый из профилей.
  cloud.config.server:
    git:
      uri: '${CONFIG_REPOSITORY_URL}/{application}-config'
      # configserver будет клонировать указанный репозиторий при запуске
      cloneOnStart: true
      defaultLabel: main
      search-paths:
        - '{profile}'

# Порт, который Spring Configuration Server будет прослушивать, ожидая запросов на получение конфигурации
server:
  port: '${CONFIG_SERVER_PORT}'

management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: always